---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

- name: 'Install build tools'
  ansible.builtin.package:
    name: '{{ hub_source_packages }}'
    state: 'present'

- name: 'Check if hub is installed'
  ansible.builtin.shell: 'which hub >>/dev/null 2>&1 ; echo $?'
  register: 'hub_exe'
  changed_when: false

- name: 'Get temporary directory for building'
  ansible.builtin.tempfile:
    state: 'directory'
    suffix: 'hub'
  register: 'hub_build'
  when:
  - '"0" not in hub_exe.stdout or hub_force_build'

- name: 'Get the source code'
  ansible.builtin.git:
    repo: 'https://github.com/github/hub.git'
    dest: '{{ hub_build.path }}/hub'
    version: '{{ hub_source_version }}'
  when:
  - 'hub_build.path is defined'

- name: 'Build the source code'
  community.general.make:
    chdir: '{{ hub_build.path }}/hub'
  when:
  - 'hub_build.path is defined'

- name: 'Do the install'
  community.general.make:
    chdir: '{{ hub_build.path }}/hub'
    target: 'install'
    params: 'prefix=/usr'
  when:
  - 'hub_build.path is defined'

- name: 'Remove the temporary directory'
  ansible.builtin.file:
    path: '{{ hub_build.path }}'
    state: 'absent'
  when:
  - 'hub_build.path is defined'
