---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

- name: "Set the OS distribution dependent variables"
  include_vars: "{{ lookup('first_found', possible_files) }}"
  vars:
    possible_files:
    - "vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "vars/{{ ansible_distribution }}.yml"
    - "vars/{{ ansible_os_family }}.yml"
    - "vars/default.yml"

- name: "Install the GitHub cli from package"
  package:
    name: "{{ hub_package }}"
    state: "{{ hub_status }}"
  when:
  - "not hub_build_from_source"

- name: "Install from source"
  include_tasks: "install-source.yml"
  when:
  - "hub_build_from_source"
